import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {ReactNode} from "react";
import MainNav from '@/components/MainNav';

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children
  }: Readonly<{
    children: ReactNode;
  }>
) {
  return (
    <html lang="en">
    <body className={cn(
      "p-4 font-sans antialiased",
      fontSans.variable
    )}>
    <MainNav/>
    {children}
    </body>
    </html>
  );
}
